# Dockerfile.api
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies by copying
# package.json and package-lock.json
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3010

CMD [ "node", "app.js" ]
